package lime;


import lime.utils.Assets;


class AssetData {

	private static var initialized:Bool = false;
	
	public static var library = new #if haxe3 Map <String, #else Hash <#end LibraryType> ();
	public static var path = new #if haxe3 Map <String, #else Hash <#end String> ();
	public static var type = new #if haxe3 Map <String, #else Hash <#end AssetType> ();	
	
	public static function initialize():Void {
		
		if (!initialized) {
			
			path.set ("assets/Audio/Ogg/bonk.OGG", "assets/Audio/Ogg/bonk.OGG");
			type.set ("assets/Audio/Ogg/bonk.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/characterselect.OGG", "assets/Audio/Ogg/characterselect.OGG");
			type.set ("assets/Audio/Ogg/characterselect.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/collectcoin.OGG", "assets/Audio/Ogg/collectcoin.OGG");
			type.set ("assets/Audio/Ogg/collectcoin.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/died.OGG", "assets/Audio/Ogg/died.OGG");
			type.set ("assets/Audio/Ogg/died.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/finalkill.OGG", "assets/Audio/Ogg/finalkill.OGG");
			type.set ("assets/Audio/Ogg/finalkill.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/fireballspawn.OGG", "assets/Audio/Ogg/fireballspawn.OGG");
			type.set ("assets/Audio/Ogg/fireballspawn.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/gameover.OGG", "assets/Audio/Ogg/gameover.OGG");
			type.set ("assets/Audio/Ogg/gameover.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/killenemy.OGG", "assets/Audio/Ogg/killenemy.OGG");
			type.set ("assets/Audio/Ogg/killenemy.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/nextlevel.OGG", "assets/Audio/Ogg/nextlevel.OGG");
			type.set ("assets/Audio/Ogg/nextlevel.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/pow.OGG", "assets/Audio/Ogg/pow.OGG");
			type.set ("assets/Audio/Ogg/pow.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/respawn.OGG", "assets/Audio/Ogg/respawn.OGG");
			type.set ("assets/Audio/Ogg/respawn.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/spawncoin.OGG", "assets/Audio/Ogg/spawncoin.OGG");
			type.set ("assets/Audio/Ogg/spawncoin.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/startgame.OGG", "assets/Audio/Ogg/startgame.OGG");
			type.set ("assets/Audio/Ogg/startgame.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/step1.OGG", "assets/Audio/Ogg/step1.OGG");
			type.set ("assets/Audio/Ogg/step1.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/step2.OGG", "assets/Audio/Ogg/step2.OGG");
			type.set ("assets/Audio/Ogg/step2.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/step3.OGG", "assets/Audio/Ogg/step3.OGG");
			type.set ("assets/Audio/Ogg/step3.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme1.OGG", "assets/Audio/Ogg/theme1.OGG");
			type.set ("assets/Audio/Ogg/theme1.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme10.OGG", "assets/Audio/Ogg/theme10.OGG");
			type.set ("assets/Audio/Ogg/theme10.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme11.OGG", "assets/Audio/Ogg/theme11.OGG");
			type.set ("assets/Audio/Ogg/theme11.OGG", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme12.OGG", "assets/Audio/Ogg/theme12.OGG");
			type.set ("assets/Audio/Ogg/theme12.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme12intro.OGG", "assets/Audio/Ogg/theme12intro.OGG");
			type.set ("assets/Audio/Ogg/theme12intro.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme2.OGG", "assets/Audio/Ogg/theme2.OGG");
			type.set ("assets/Audio/Ogg/theme2.OGG", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme3.OGG", "assets/Audio/Ogg/theme3.OGG");
			type.set ("assets/Audio/Ogg/theme3.OGG", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme4.OGG", "assets/Audio/Ogg/theme4.OGG");
			type.set ("assets/Audio/Ogg/theme4.OGG", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme5.OGG", "assets/Audio/Ogg/theme5.OGG");
			type.set ("assets/Audio/Ogg/theme5.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme6.OGG", "assets/Audio/Ogg/theme6.OGG");
			type.set ("assets/Audio/Ogg/theme6.OGG", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme7.OGG", "assets/Audio/Ogg/theme7.OGG");
			type.set ("assets/Audio/Ogg/theme7.OGG", Reflect.field (AssetType, "music".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme8.OGG", "assets/Audio/Ogg/theme8.OGG");
			type.set ("assets/Audio/Ogg/theme8.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme8intro.OGG", "assets/Audio/Ogg/theme8intro.OGG");
			type.set ("assets/Audio/Ogg/theme8intro.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/theme9.OGG", "assets/Audio/Ogg/theme9.OGG");
			type.set ("assets/Audio/Ogg/theme9.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/Audio/Ogg/titlescreen.OGG", "assets/Audio/Ogg/titlescreen.OGG");
			type.set ("assets/Audio/Ogg/titlescreen.OGG", Reflect.field (AssetType, "sound".toUpperCase ()));
			path.set ("assets/bgcolor.png", "assets/bgcolor.png");
			type.set ("assets/bgcolor.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/black.png", "assets/black.png");
			type.set ("assets/black.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Dpad.png", "assets/Dpad.png");
			type.set ("assets/Dpad.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/1up0.png", "assets/Sprites/1up0.png");
			type.set ("assets/Sprites/1up0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/akyu0.png", "assets/Sprites/akyu0.png");
			type.set ("assets/Sprites/akyu0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/alice0.png", "assets/Sprites/alice0.png");
			type.set ("assets/Sprites/alice0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/aliceALT0.png", "assets/Sprites/aliceALT0.png");
			type.set ("assets/Sprites/aliceALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/aya0.png", "assets/Sprites/aya0.png");
			type.set ("assets/Sprites/aya0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/barrier0.png", "assets/Sprites/barrier0.png");
			type.set ("assets/Sprites/barrier0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/BG0.png", "assets/Sprites/BG0.png");
			type.set ("assets/Sprites/BG0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/BG1.png", "assets/Sprites/BG1.png");
			type.set ("assets/Sprites/BG1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/BG2.png", "assets/Sprites/BG2.png");
			type.set ("assets/Sprites/BG2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/BG3.png", "assets/Sprites/BG3.png");
			type.set ("assets/Sprites/BG3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/BG4.png", "assets/Sprites/BG4.png");
			type.set ("assets/Sprites/BG4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/BG5.png", "assets/Sprites/BG5.png");
			type.set ("assets/Sprites/BG5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/block0.png", "assets/Sprites/block0.png");
			type.set ("assets/Sprites/block0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Blueufo0.png", "assets/Sprites/Blueufo0.png");
			type.set ("assets/Sprites/Blueufo0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/bullet0.png", "assets/Sprites/bullet0.png");
			type.set ("assets/Sprites/bullet0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/byakuren0.png", "assets/Sprites/byakuren0.png");
			type.set ("assets/Sprites/byakuren0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/chen0.png", "assets/Sprites/chen0.png");
			type.set ("assets/Sprites/chen0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/chiyuri0.png", "assets/Sprites/chiyuri0.png");
			type.set ("assets/Sprites/chiyuri0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/cirno0.png", "assets/Sprites/cirno0.png");
			type.set ("assets/Sprites/cirno0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/darkness0.png", "assets/Sprites/darkness0.png");
			type.set ("assets/Sprites/darkness0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen0.png", "assets/Sprites/EChen0.png");
			type.set ("assets/Sprites/EChen0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen1.png", "assets/Sprites/EChen1.png");
			type.set ("assets/Sprites/EChen1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen2.png", "assets/Sprites/EChen2.png");
			type.set ("assets/Sprites/EChen2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen3.png", "assets/Sprites/EChen3.png");
			type.set ("assets/Sprites/EChen3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen4.png", "assets/Sprites/EChen4.png");
			type.set ("assets/Sprites/EChen4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen5.png", "assets/Sprites/EChen5.png");
			type.set ("assets/Sprites/EChen5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen6.png", "assets/Sprites/EChen6.png");
			type.set ("assets/Sprites/EChen6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EChen7.png", "assets/Sprites/EChen7.png");
			type.set ("assets/Sprites/EChen7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ECirno0.png", "assets/Sprites/ECirno0.png");
			type.set ("assets/Sprites/ECirno0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/eirin0.png", "assets/Sprites/eirin0.png");
			type.set ("assets/Sprites/eirin0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EKeine0.png", "assets/Sprites/EKeine0.png");
			type.set ("assets/Sprites/EKeine0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EKeineex0.png", "assets/Sprites/EKeineex0.png");
			type.set ("assets/Sprites/EKeineex0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/EKeineexflipped0.png", "assets/Sprites/EKeineexflipped0.png");
			type.set ("assets/Sprites/EKeineexflipped0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ellen0.png", "assets/Sprites/ellen0.png");
			type.set ("assets/Sprites/ellen0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/elly0.png", "assets/Sprites/elly0.png");
			type.set ("assets/Sprites/elly0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan0.png", "assets/Sprites/ERan0.png");
			type.set ("assets/Sprites/ERan0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan1.png", "assets/Sprites/ERan1.png");
			type.set ("assets/Sprites/ERan1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan2.png", "assets/Sprites/ERan2.png");
			type.set ("assets/Sprites/ERan2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan3.png", "assets/Sprites/ERan3.png");
			type.set ("assets/Sprites/ERan3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan4.png", "assets/Sprites/ERan4.png");
			type.set ("assets/Sprites/ERan4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan5.png", "assets/Sprites/ERan5.png");
			type.set ("assets/Sprites/ERan5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan6.png", "assets/Sprites/ERan6.png");
			type.set ("assets/Sprites/ERan6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ERan7.png", "assets/Sprites/ERan7.png");
			type.set ("assets/Sprites/ERan7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/firecirno0.png", "assets/Sprites/firecirno0.png");
			type.set ("assets/Sprites/firecirno0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/flames0.png", "assets/Sprites/flames0.png");
			type.set ("assets/Sprites/flames0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/flames1.png", "assets/Sprites/flames1.png");
			type.set ("assets/Sprites/flames1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/flames2.png", "assets/Sprites/flames2.png");
			type.set ("assets/Sprites/flames2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/flandre0.png", "assets/Sprites/flandre0.png");
			type.set ("assets/Sprites/flandre0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/futo0.png", "assets/Sprites/futo0.png");
			type.set ("assets/Sprites/futo0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Gap0.png", "assets/Sprites/Gap0.png");
			type.set ("assets/Sprites/Gap0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/gengetsu0.png", "assets/Sprites/gengetsu0.png");
			type.set ("assets/Sprites/gengetsu0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Greenufo0.png", "assets/Sprites/Greenufo0.png");
			type.set ("assets/Sprites/Greenufo0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer0.png", "assets/Sprites/hammer0.png");
			type.set ("assets/Sprites/hammer0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer1.png", "assets/Sprites/hammer1.png");
			type.set ("assets/Sprites/hammer1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer2.png", "assets/Sprites/hammer2.png");
			type.set ("assets/Sprites/hammer2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer3.png", "assets/Sprites/hammer3.png");
			type.set ("assets/Sprites/hammer3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer4.png", "assets/Sprites/hammer4.png");
			type.set ("assets/Sprites/hammer4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer5.png", "assets/Sprites/hammer5.png");
			type.set ("assets/Sprites/hammer5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer6.png", "assets/Sprites/hammer6.png");
			type.set ("assets/Sprites/hammer6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hammer7.png", "assets/Sprites/hammer7.png");
			type.set ("assets/Sprites/hammer7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hatate0.png", "assets/Sprites/hatate0.png");
			type.set ("assets/Sprites/hatate0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/hina0.png", "assets/Sprites/hina0.png");
			type.set ("assets/Sprites/hina0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/icyblock0.png", "assets/Sprites/icyblock0.png");
			type.set ("assets/Sprites/icyblock0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/iku0.png", "assets/Sprites/iku0.png");
			type.set ("assets/Sprites/iku0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kagerou0.png", "assets/Sprites/kagerou0.png");
			type.set ("assets/Sprites/kagerou0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kaguya0.png", "assets/Sprites/kaguya0.png");
			type.set ("assets/Sprites/kaguya0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kana0.png", "assets/Sprites/kana0.png");
			type.set ("assets/Sprites/kana0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kasen0.png", "assets/Sprites/kasen0.png");
			type.set ("assets/Sprites/kasen0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/keine0.png", "assets/Sprites/keine0.png");
			type.set ("assets/Sprites/keine0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kogasa0.png", "assets/Sprites/kogasa0.png");
			type.set ("assets/Sprites/kogasa0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/koishi0.png", "assets/Sprites/koishi0.png");
			type.set ("assets/Sprites/koishi0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kokoro0.png", "assets/Sprites/kokoro0.png");
			type.set ("assets/Sprites/kokoro0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/komachi0.png", "assets/Sprites/komachi0.png");
			type.set ("assets/Sprites/komachi0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kosuzu0.png", "assets/Sprites/kosuzu0.png");
			type.set ("assets/Sprites/kosuzu0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kotohime0.png", "assets/Sprites/kotohime0.png");
			type.set ("assets/Sprites/kotohime0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/kurumi0.png", "assets/Sprites/kurumi0.png");
			type.set ("assets/Sprites/kurumi0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/letty0.png", "assets/Sprites/letty0.png");
			type.set ("assets/Sprites/letty0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/lily0.png", "assets/Sprites/lily0.png");
			type.set ("assets/Sprites/lily0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/luize0.png", "assets/Sprites/luize0.png");
			type.set ("assets/Sprites/luize0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/lunachild0.png", "assets/Sprites/lunachild0.png");
			type.set ("assets/Sprites/lunachild0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/mai0.png", "assets/Sprites/mai0.png");
			type.set ("assets/Sprites/mai0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/mamizou0.png", "assets/Sprites/mamizou0.png");
			type.set ("assets/Sprites/mamizou0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/marisa0.png", "assets/Sprites/marisa0.png");
			type.set ("assets/Sprites/marisa0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/marisaALT0.png", "assets/Sprites/marisaALT0.png");
			type.set ("assets/Sprites/marisaALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/medicine0.png", "assets/Sprites/medicine0.png");
			type.set ("assets/Sprites/medicine0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/meiling0.png", "assets/Sprites/meiling0.png");
			type.set ("assets/Sprites/meiling0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/meilingALT0.png", "assets/Sprites/meilingALT0.png");
			type.set ("assets/Sprites/meilingALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/meira0.png", "assets/Sprites/meira0.png");
			type.set ("assets/Sprites/meira0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/mima0.png", "assets/Sprites/mima0.png");
			type.set ("assets/Sprites/mima0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/minoriko0.png", "assets/Sprites/minoriko0.png");
			type.set ("assets/Sprites/minoriko0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/mokou0.png", "assets/Sprites/mokou0.png");
			type.set ("assets/Sprites/mokou0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/momiji0.png", "assets/Sprites/momiji0.png");
			type.set ("assets/Sprites/momiji0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/mugetsu0.png", "assets/Sprites/mugetsu0.png");
			type.set ("assets/Sprites/mugetsu0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/murasa0.png", "assets/Sprites/murasa0.png");
			type.set ("assets/Sprites/murasa0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Mystia0.png", "assets/Sprites/Mystia0.png");
			type.set ("assets/Sprites/Mystia0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Mystia1.png", "assets/Sprites/Mystia1.png");
			type.set ("assets/Sprites/Mystia1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Mystiaflipped0.png", "assets/Sprites/Mystiaflipped0.png");
			type.set ("assets/Sprites/Mystiaflipped0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/nazrin0.png", "assets/Sprites/nazrin0.png");
			type.set ("assets/Sprites/nazrin0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/nitori0.png", "assets/Sprites/nitori0.png");
			type.set ("assets/Sprites/nitori0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/nue0.png", "assets/Sprites/nue0.png");
			type.set ("assets/Sprites/nue0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/orange0.png", "assets/Sprites/orange0.png");
			type.set ("assets/Sprites/orange0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/orin0.png", "assets/Sprites/orin0.png");
			type.set ("assets/Sprites/orin0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/parsee0.png", "assets/Sprites/parsee0.png");
			type.set ("assets/Sprites/parsee0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/patchouli0.png", "assets/Sprites/patchouli0.png");
			type.set ("assets/Sprites/patchouli0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/pika0.png", "assets/Sprites/pika0.png");
			type.set ("assets/Sprites/pika0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Point0.png", "assets/Sprites/Point0.png");
			type.set ("assets/Sprites/Point0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/POW0.png", "assets/Sprites/POW0.png");
			type.set ("assets/Sprites/POW0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/prinny0.png", "assets/Sprites/prinny0.png");
			type.set ("assets/Sprites/prinny0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/ran0.png", "assets/Sprites/ran0.png");
			type.set ("assets/Sprites/ran0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/RedFairy0.png", "assets/Sprites/RedFairy0.png");
			type.set ("assets/Sprites/RedFairy0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/RedFairyflipped0.png", "assets/Sprites/RedFairyflipped0.png");
			type.set ("assets/Sprites/RedFairyflipped0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/Redufo0.png", "assets/Sprites/Redufo0.png");
			type.set ("assets/Sprites/Redufo0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/reimu0.png", "assets/Sprites/reimu0.png");
			type.set ("assets/Sprites/reimu0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/reimuALT0.png", "assets/Sprites/reimuALT0.png");
			type.set ("assets/Sprites/reimuALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/reisen0.png", "assets/Sprites/reisen0.png");
			type.set ("assets/Sprites/reisen0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/remilia0.png", "assets/Sprites/remilia0.png");
			type.set ("assets/Sprites/remilia0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/rika0.png", "assets/Sprites/rika0.png");
			type.set ("assets/Sprites/rika0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/rikako0.png", "assets/Sprites/rikako0.png");
			type.set ("assets/Sprites/rikako0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/rumia0.png", "assets/Sprites/rumia0.png");
			type.set ("assets/Sprites/rumia0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sakuya0.png", "assets/Sprites/sakuya0.png");
			type.set ("assets/Sprites/sakuya0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sakuyaALT0.png", "assets/Sprites/sakuyaALT0.png");
			type.set ("assets/Sprites/sakuyaALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sanae0.png", "assets/Sprites/sanae0.png");
			type.set ("assets/Sprites/sanae0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sanaeALT0.png", "assets/Sprites/sanaeALT0.png");
			type.set ("assets/Sprites/sanaeALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sarah0.png", "assets/Sprites/sarah0.png");
			type.set ("assets/Sprites/sarah0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/satori0.png", "assets/Sprites/satori0.png");
			type.set ("assets/Sprites/satori0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/seiga0.png", "assets/Sprites/seiga0.png");
			type.set ("assets/Sprites/seiga0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/seija0.png", "assets/Sprites/seija0.png");
			type.set ("assets/Sprites/seija0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sekibanki0.png", "assets/Sprites/sekibanki0.png");
			type.set ("assets/Sprites/sekibanki0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/shanghai0.png", "assets/Sprites/shanghai0.png");
			type.set ("assets/Sprites/shanghai0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/shikieiki0.png", "assets/Sprites/shikieiki0.png");
			type.set ("assets/Sprites/shikieiki0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/shinmyoumaru0.png", "assets/Sprites/shinmyoumaru0.png");
			type.set ("assets/Sprites/shinmyoumaru0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/shizuha0.png", "assets/Sprites/shizuha0.png");
			type.set ("assets/Sprites/shizuha0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/shou0.png", "assets/Sprites/shou0.png");
			type.set ("assets/Sprites/shou0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/starsaphire0.png", "assets/Sprites/starsaphire0.png");
			type.set ("assets/Sprites/starsaphire0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/suika0.png", "assets/Sprites/suika0.png");
			type.set ("assets/Sprites/suika0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/sunnymilk0.png", "assets/Sprites/sunnymilk0.png");
			type.set ("assets/Sprites/sunnymilk0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/suwako0.png", "assets/Sprites/suwako0.png");
			type.set ("assets/Sprites/suwako0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table0.png", "assets/Sprites/table0.png");
			type.set ("assets/Sprites/table0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table1.png", "assets/Sprites/table1.png");
			type.set ("assets/Sprites/table1.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table2.png", "assets/Sprites/table2.png");
			type.set ("assets/Sprites/table2.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table3.png", "assets/Sprites/table3.png");
			type.set ("assets/Sprites/table3.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table4.png", "assets/Sprites/table4.png");
			type.set ("assets/Sprites/table4.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table5.png", "assets/Sprites/table5.png");
			type.set ("assets/Sprites/table5.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table6.png", "assets/Sprites/table6.png");
			type.set ("assets/Sprites/table6.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/table7.png", "assets/Sprites/table7.png");
			type.set ("assets/Sprites/table7.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/tenshi0.png", "assets/Sprites/tenshi0.png");
			type.set ("assets/Sprites/tenshi0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/tewi0.png", "assets/Sprites/tewi0.png");
			type.set ("assets/Sprites/tewi0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/titlescreen0.png", "assets/Sprites/titlescreen0.png");
			type.set ("assets/Sprites/titlescreen0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/tokiko0.png", "assets/Sprites/tokiko0.png");
			type.set ("assets/Sprites/tokiko0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/utsuho0.png", "assets/Sprites/utsuho0.png");
			type.set ("assets/Sprites/utsuho0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/wriggle0.png", "assets/Sprites/wriggle0.png");
			type.set ("assets/Sprites/wriggle0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yoshika0.png", "assets/Sprites/yoshika0.png");
			type.set ("assets/Sprites/yoshika0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/youmu0.png", "assets/Sprites/youmu0.png");
			type.set ("assets/Sprites/youmu0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yukari0.png", "assets/Sprites/yukari0.png");
			type.set ("assets/Sprites/yukari0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yuki0.png", "assets/Sprites/yuki0.png");
			type.set ("assets/Sprites/yuki0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yumeko0.png", "assets/Sprites/yumeko0.png");
			type.set ("assets/Sprites/yumeko0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yumemi0.png", "assets/Sprites/yumemi0.png");
			type.set ("assets/Sprites/yumemi0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yuuka0.png", "assets/Sprites/yuuka0.png");
			type.set ("assets/Sprites/yuuka0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yuukaALT0.png", "assets/Sprites/yuukaALT0.png");
			type.set ("assets/Sprites/yuukaALT0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			path.set ("assets/Sprites/yuyuko0.png", "assets/Sprites/yuyuko0.png");
			type.set ("assets/Sprites/yuyuko0.png", Reflect.field (AssetType, "image".toUpperCase ()));
			
			
			initialized = true;
			
		} //!initialized
		
	} //initialize
	
	
} //AssetData
